### ISSUE TITLE
Request implementation of RemoveDevice

### ISSUE THREAD

**Issue by daviessm** [intel-iot-devkit/tinyb#128]
The recent versions of BlueZ cache all discovered (maybe connected?) devices and return them in a scan even after they've long gone out of range or been switched off. This causes exceptions from tinyb when trying to connect to them, unaware that they aren't actually there.

BlueZ provides the RemoveDevice DBus method and remove_device C method to forget these. Could this be implemented in tinyb?

**Comment by impala454** [comment]
BlueZ does not do the caching, dbus does.  Agreed that the feature would be good to add, just wanted to clarify.

**Comment by petreeftime** [comment]
This is already implemented, if I understand the request correctly: https://github.com/intel-iot-devkit/tinyb/commit/daa37a0e09bc79c6f21a205b93a211e33042e48b

**Comment by daviessm** [comment]
Oh, thanks. I'll give it a go. It isn't in the documentation at http://iotdk.intel.com/docs/master/tinyb/java/classtinyb_1_1BluetoothDevice.html - that's why I didn't see it.

**Comment by daviessm** [comment]
Yes, that does what I was looking for.
