### ISSUE TITLE
Native library is out of date

### ISSUE THREAD

**Issue by AxelUlmestig** [intel-iot-devkit/tinyb#46]
EDIT: I realized there was another cmake script to be run in the java examples folder. Running this along with the "-DCMAKE_INSTALLPREFIX=/usr .." solved the issue.

Hi

I've been trying to get the tinyb java example to run but I've been running in to some problems. When I Run it it gives me this response:

`    
    root@Edison1:~# make run
    
    cd build && java -jar tinyb_local.jar XX:XX:XX:XX:XX:XX
    
    Exception in thread "main" java.lang.RuntimeException: Native library is out of date. Please update the native library.
    
        at tinyb.BluetoothManager.getBluetoothManager(BluetoothManager.java:234)
    
        at HelloTinyB.main(HelloTinyB.java:109)
    
    Makefile:25: recipe for target 'run' failed
`

(I put the commands in a Makefile to be able to experiment more efficiently.)
I added two printouts in the BluetoothManager class to see the versions:

`
    
    String nativeAPIVersion = getNativeAPIVersion();
    
    String APIVersion = BluetoothManager.class.getPackage().getSpecificationVersion();
    
    System.out.println(nativeAPIVersion);
    
    System.out.println(APIVersion);
    
    if (APIVersion.equals(nativeAPIVersion) == false) {`
    
It then gives me this:

`
    
    root@Edison1:~# make run
    
    cd build && java -jar tinyb_local.jar XX:XX:XX:XX:XX:XX
    
    nativeAPIVersion: 0.4
    
    APIVersion: 0.5.0-4-g22c1af1.0.5.0-4-g22c1af1
    
    Exception in thread "main" java.lang.RuntimeException: Native library is out of date. Please update the native library.
    
    at tinyb.BluetoothManager.getBluetoothManager(BluetoothManager.java:234)
    
    at HelloTinyB.main(HelloTinyB.java:109)
    
    Makefile:25: recipe for target 'run' failed
    
    make: *** [run] Error 1
`

Below are the output I got from the build process.
**building tinyb.jar**

`
    mkdir -p tinyb/build
    
    cd tinyb/build && cmake .. -DBUILDJAVA=ON
    
    $(MAKE) -C tinyb/build/
    
    $(MAKE) -C tinyb/build/ MAKEFLAGS="install"`

`
    mkdir -p tinyb/build
    
    cd tinyb/build && cmake .. -DBUILDJAVA=ON
    
    -- JNI_INCLUDE_DIRS=/usr/lib/jvm/java-8-openjdk/include;/usr/lib/jvm/java-8-
    
    openjdk/include/linux;/usr/lib/jvm/java-8-openjdk/include
    
    -- JNI_LIBRARIES=/usr/lib/jvm/java-8-openjdk/jre/lib/i386/libjawt.so;/usr/lib/jvm/java-8-
    
    openjdk/jre/lib/i386/libjvm.so
    
    -- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE)
    
    -- Configuring done
    
    -- Generating done
    
    -- Build files have been written to: /home/root/tinyb/build
    
    make -C tinyb/build/
    
    make[1]: Entering directory '/home/root/tinyb/build'
    
    make[2]: Entering directory '/home/root/tinyb/build'
    
    make[3]: Entering directory '/home/root/tinyb/build'
    
    make[3]: Leaving directory '/home/root/tinyb/build'
    
    make[3]: Entering directory '/home/root/tinyb/build'
    
    [  2%] Building Java objects for tinybjar.jar
    
    [  4%] Generating CMakeFiles/tinybjar.dir/java_class_filelist
    
    [  6%] Creating Java archive tinyb.jar
    
    Generating JNI headers..
    
    make[3]: Leaving directory '/home/root/tinyb/build'
    
    [  6%] Built target tinybjar
    
    make[3]: Entering directory '/home/root/tinyb/build'
    
    make[3]: Leaving directory '/home/root/tinyb/build'
    
    [ 32%] Built target tinyb
    
    make[3]: Entering directory '/home/root/tinyb/build'
    
    make[3]: Leaving directory '/home/root/tinyb/build'
    
    [54%] Built target javatinyb
    
    make[3]: Entering directory '/home/root/tinyb/build'
    
    make[3]: Leaving directory '/home/root/tinyb/build'
    
    make[3]: Entering directory '/home/root/tinyb/build'
    
    [56%] Building Java objects for AsyncTinyB.jar
    
    [ 58%] Generating CMakeFiles/AsyncTinyB.dir/java_class_filelist
    
    [ 60%] Creating Java archive AsyncTinyB.jar
    
    make[3]: Leaving directory '/home/root/tinyb/build'
    
    [ 60%] Built target AsyncTinyB
    
    make[3]: Entering directory '/home/root/tinyb/build'
    
    make[3]: Leaving directory '/home/root/tinyb/build'
    
    make[3]: Entering directory '/home/root/tinyb/build'
    
    [ 62%] Building Java objects for HelloTinyB.jar
    
    [ 64%] Generating CMakeFiles/HelloTinyB.dir/java_class_filelist
    
    [ 66%] Creating Java archive HelloTinyB.jar
    
    make[3]: Leaving directory '/home/root/tinyb/build'
    
    [ 66%] Built target HelloTinyB
    
    make[3]: Entering directory '/home/root/tinyb/build'
    
    make[3]: Leaving directory '/home/root/tinyb/build'
    
    make[3]: Entering directory '/home/root/tinyb/build'
    
    [ 68%] Building Java objects for Notification.jar
    
    [ 70%] Generating CMakeFiles/Notification.dir/java_class_filelist
    
    [ 72%] Creating Java archive Notification.jar
    
    make[3]: Leaving directory '/home/root/tinyb/build'
    
    [ 72%] Built target Notification
    
    make[3]: Entering directory '/home/root/tinyb/build'
    
    make[3]: Leaving directory '/home/root/tinyb/build'
    
    [ 76%] Built target asynctinyb
    
    make[3]: Entering directory '/home/root/tinyb/build'
    
    make[3]: Leaving directory '/home/root/tinyb/build'
    
    [ 80%] Built target checkinit
    
    make[3]: Entering directory '/home/root/tinyb/build'
    
    make[3]: Leaving directory '/home/root/tinyb/build'
    
    [ 84%] Built target esstinyb
    
    make[3]: Entering directory '/home/root/tinyb/build'
    
    make[3]: Leaving directory '/home/root/tinyb/build'
    
    [ 88%] Built target hellotinyb
    
    make[3]: Entering directory '/home/root/tinyb/build'
    
    make[3]: Leaving directory '/home/root/tinyb/build'
    
    [ 92%] Built target list_mfg
    
    make[3]: Entering directory '/home/root/tinyb/build'
    
    make[3]: Leaving directory '/home/root/tinyb/build'
    
    [ 96%] Built target notifications
    
    make[3]: Entering directory '/home/root/tinyb/build'
    
    make[3]: Leaving directory '/home/root/tinyb/build'
    
    [100%] Built target uuid
    
    make[2]: Leaving directory '/home/root/tinyb/build'
    
    make[1]: Leaving directory '/home/root/tinyb/build'
    
    make -C tinyb/build/ MAKEFLAGS="install"
    
    make[1]: Entering directory '/home/root/tinyb/build'
        
    make -f CMakeFiles/Makefile2 all
    
    make -f java/CMakeFiles/tinybjar.dir/build.make java/CMakeFiles/tinybjar.dir/depend
    
    make -f java/CMakeFiles/tinybjar.dir/build.make java/CMakeFiles/tinybjar.dir/build
    
    make -f src/CMakeFiles/tinyb.dir/build.make src/CMakeFiles/tinyb.dir/depend
    
    make -f src/CMakeFiles/tinyb.dir/build.make src/CMakeFiles/tinyb.dir/build
    
    make -f java/jni/CMakeFiles/javatinyb.dir/build.make java/jni/CMakeFiles/javatinyb.dir/depend
    
    make -f java/jni/CMakeFiles/javatinyb.dir/build.make java/jni/CMakeFiles/javatinyb.dir/build
    
    make -f examples/java/CMakeFiles/AsyncTinyB.dir/build.make 
    
    examples/java/CMakeFiles/AsyncTinyB.dir/depend
    
    make -f examples/java/CMakeFiles/AsyncTinyB.dir/build.make 
    
    examples/java/CMakeFiles/AsyncTinyB.dir/build
    
    make -f examples/java/CMakeFiles/HelloTinyB.dir/build.make 
    
    examples/java/CMakeFiles/HelloTinyB.dir/depend
    
    make -f examples/java/CMakeFiles/HelloTinyB.dir/build.make 
    
    examples/java/CMakeFiles/HelloTinyB.dir/build
    
    make -f examples/java/CMakeFiles/Notification.dir/build.make 
    
    examples/java/CMakeFiles/Notification.dir/depend
    
    make -f examples/java/CMakeFiles/Notification.dir/build.make 
    
    examples/java/CMakeFiles/Notification.dir/build
    
    make -f examples/CMakeFiles/asynctinyb.dir/build.make examples/CMakeFiles/asynctinyb.dir/depend
    
    make -f examples/CMakeFiles/asynctinyb.dir/build.make examples/CMakeFiles/asynctinyb.dir/build
    
    make -f examples/CMakeFiles/checkinit.dir/build.make examples/CMakeFiles/checkinit.dir/depend
    
    make -f examples/CMakeFiles/checkinit.dir/build.make examples/CMakeFiles/checkinit.dir/build
    
    make -f examples/CMakeFiles/esstinyb.dir/build.make examples/CMakeFiles/esstinyb.dir/depend
    
    make -f examples/CMakeFiles/esstinyb.dir/build.make examples/CMakeFiles/esstinyb.dir/build
    
    make -f examples/CMakeFiles/hellotinyb.dir/build.make examples/CMakeFiles/hellotinyb.dir/depend
    
    make -f examples/CMakeFiles/hellotinyb.dir/build.make examples/CMakeFiles/hellotinyb.dir/build
    
    make -f examples/CMakeFiles/list_mfg.dir/build.make examples/CMakeFiles/list_mfg.dir/depend
    
    make -f examples/CMakeFiles/list_mfg.dir/build.make examples/CMakeFiles/list_mfg.dir/build
    
    make -f examples/CMakeFiles/notifications.dir/build.make 
    
    examples/CMakeFiles/notifications.dir/depend
    
    make -f examples/CMakeFiles/notifications.dir/build.make         
    
    examples/CMakeFiles/notifications.dir/build
    
    make -f examples/CMakeFiles/uuid.dir/build.make examples/CMakeFiles/uuid.dir/depend
    
    make -f examples/CMakeFiles/uuid.dir/build.make examples/CMakeFiles/uuid.dir/build
    
    make[1]: Leaving directory '/home/root/tinyb/build'
`
**building the example jar**

` 
    mkdir -p build
        
    javac -d build/ -classpath tinyb/build/java/tinyb.jar tinyb/examples/java/*.java
    
    cp MANIFEST.MF build/
    
    cd build && jar cfm tinyb_local.jar MANIFEST.MF *.class
`

**Makefile**
`
    make:
        
        mkdir -p build
        
        javac -d build/ -classpath tinyb/build/java/tinyb.jar tinyb/examples/java/*.java
        
        cp MANIFEST.MF build/
        
        cd build && jar cfm tinyb_local.jar MANIFEST.MF *.class
        
    install:
        
        mkdir -p tinyb/build
        
        cd tinyb/build && cmake .. -DBUILDJAVA=ON
        
        $(MAKE) -C tinyb/build/
        
        $(MAKE) -C tinyb/build/ MAKEFLAGS="install"
        
    run:
                
        cd build && java -jar tinyb_local.jar ${MAC_ADDR}
        
    clean:
            
        rm -r build/
`

**MANIFEST.MF**

` 

    Manifest-Version: 1.0
    
    Main-Class: HelloTinyB
    
    Class-Path: ../tinyb/build/java/tinyb.jar
`

Sorry for the long post. Does anyone have any similar experience or idea what might be wrong?

**Comment by ghost** [comment]
I have the exact same issue. @AxelUlmestig why was this closed? How did you resolve it?
