### ISSUE TITLE
Connections between raspberry pi and multiple Ti SensorTag devices are not stable

### ISSUE THREAD

**Issue by tanvn** [intel-iot-devkit/tinyb#90]
I am now using tinyb to connect to multiple Ti SensorTag (CC2650) devices.
I am successful at connecting and reading data from Sensortag devices.
But my problem is when I have 2 (or above) devices concurrently connecting to my Raspberry Pi,
only one connection is stable, the other's connection are not stable.
They disconnected to my Raspberry Pi, them  my Raspberry found them, re-connect again,
then they disconnected again and again...

I think maybe it's not because of tinyb, but I don't have any clues what happens, so it will be great if there is anyone who knows what could be the cause of my problem.
Thanks a lot.

**Comment by impala454** [comment]
I know this isn't the nicest answer but in my experience (having connected 12 various BLE devices at once) you simply have to make your code handle disconnections and reconnections.
