### ISSUE TITLE
[bug] Memory leak : disableConnectedNotifications and disableServicesResolvedNotifications do not unregister the callback  object passed through the corresponding enable method.

### ISSUE THREAD

**Issue by tanvn** [intel-iot-devkit/tinyb#92]
I found that even when I call disableConnectedNotifications and disableServicesResolvedNotifications on my devices then register new Notification callback objects, the previous callback objects are not unregistered, and causes the problem of there are many callback objects are left and when my devices disconnected then re-connected again, the notifications are fired more than once.
I think the more often the device disconnect - re-connect, the more callback objects are left and don't get garbage-collected, so there will be memory leak ?
![0029-03-22 19 23 17](https://cloud.githubusercontent.com/assets/3862870/24193339/4a75b4f4-0f35-11e7-8dd3-21d4b6a0020b.png)
A reply will be greatly appreciated.

**Comment by petreeftime** [comment]
This should have been fixed by #107
