### ISSUE TITLE
BluetoothGattCharacteristic.enableValueNotifications() fails with "Operation is not supported"

### ISSUE THREAD

**Issue by swilson** [intel-iot-devkit/tinyb#95]
I'm trying to use tinyb on Ubuntu, and BluetoothGattCharacteristic.enableValueNotifications() always fails with:

tinyb.BluetoothException: GDBus.Error:org.bluez.Error.NotSupported: Operation is not supported

This is presumably coming from chr_start_notify() in bluez/tools/gatt-service.c. I can't seem to find a version of bluez that actually supports StartNotify(); is there one? If not, how does the Notification.java example work?

**Comment by petreeftime** [comment]
It's supported in BlueZ 5.42 or newer for sure, since it worked when I tested it.

**Comment by swilson** [comment]
What platform was that on? Perhaps it is using a fork of BlueZ? It appears the main version (https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/tools/gatt-service.c) doesn't have support for this.

**Comment by swilson** [comment]
Had an issue with my service table; tinyb works fine.
